function(generate_cmipfembvbin_config_files)

  include(CMakePackageConfigHelpers)

  configure_package_config_file(
    "${CMAKE_MODULE_PATH}/CMIPFEMBVBINConfig.cmake.in"
    "${PROJECT_BINARY_DIR}/${CMIPFEMBVBIN_INSTALL_CMAKE_DIR}/CMIPFEMBVBINConfig.cmake"
    INSTALL_DESTINATION "${CMIPFEMBVBIN_INSTALL_CMAKE_DIR}"
    PATH_VARS
    CMIPFEMBVBIN_INSTALL_CMAKE_DIR
    CMIPFEMBVBIN_INSTALL_INCLUDE_DIR
    )

  install(FILES "${PROJECT_BINARY_DIR}/${CMIPFEMBVBIN_INSTALL_CMAKE_DIR}/CMIPFEMBVBINConfig.cmake"
    DESTINATION ${CMIPFEMBVBIN_INSTALL_CMAKE_DIR})

  install(EXPORT CMIPFEMBVBINTargets
    NAMESPACE CMIPFEMBVBIN::
    DESTINATION ${CMIPFEMBVBIN_INSTALL_CMAKE_DIR})

  write_basic_package_version_file(
    "${PROJECT_BINARY_DIR}/${CMIPFEMBVBIN_INSTALL_CMAKE_DIR}/CMIPFEMBVBINConfigVersion.cmake"
    VERSION "${CMIPFEMBVBIN_VERSION}"
    COMPATIBILITY SameMajorVersion)

  install(FILES "${PROJECT_BINARY_DIR}/${CMIPFEMBVBIN_INSTALL_CMAKE_DIR}/CMIPFEMBVBINConfigVersion.cmake"
    DESTINATION ${CMIPFEMBVBIN_INSTALL_CMAKE_DIR})

endfunction()
